[project]
name = "discord-webhook-flask"
version = "1.0.0"
description = "Discord webhook service using Flask"
requires-python = ">=3.14"
dependencies = [
    "flask==3.1.2",
    "gunicorn==23.0.0",
    "pynacl==1.6.2",
    "google-cloud-pubsub==2.34.0",
]
